# AUTOGENERATED! DO NOT EDIT! File to edit: 04_tests.ipynb (unless otherwise specified).

__all__ = ['identity_ham']

# Cell
from numpy.random import random_sample
from numpy import array
from numpy.testing import assert_allclose
from .core import ihu, y_der, check_for_stupidity
from .herm import rand_herm_ndarray, test_herm_ndarray
from .unitary import rand_unitary_ndarray, test_unitary_ndarray

# Cell
def identity_ham(t):
    iden = array(shape(2, 2))
    return iden