# AUTOGENERATED! DO NOT EDIT! File to edit: 04_tests.ipynb (unless otherwise specified).

__all__ = ['zero_ham', 'u0', 'evolution_time', 'no_time_step_for_eval', 'identity_ham', 'u0', 'evolution_time',
           'no_time_step_for_eval']

# Cell
from numpy.random import random_sample
from numpy import array, identity, zeros
from numpy.testing import assert_allclose
from .core import ihu, y_der, check_for_stupidity
from .herm import rand_herm_ndarray, test_herm_ndarray
from .unitary import rand_unitary_ndarray, test_unitary_ndarray

# Cell
def zero_ham(t):
    zerodha = zeros((2,2), dtype=complex)
    return zerodha

# Cell
# u0 = rand_unitary_ndarray((2,2))
u0 = array([[1.+0.j, 0.+0.j],
           [0.+0.j, 1.+0.j]])
evolution_time = 5
no_time_step_for_eval = 100

# Cell
def identity_ham(t):
    iden = identity(2, dtype=complex)
    return iden

# Cell
u0 = rand_unitary_ndarray((2,2))
evolution_time = 5
no_time_step_for_eval = 100