# AUTOGENERATED! DO NOT EDIT! File to edit: 04_tests.ipynb (unless otherwise specified).

__all__ = ['identity_ham', 'u0', 'evolution_time', 'no_time_step_for_eval']

# Cell
from numpy.random import random_sample
from numpy import array, identity
from numpy.testing import assert_allclose
from .core import ihu, y_der, check_for_stupidity
from .herm import rand_herm_ndarray, test_herm_ndarray
from .unitary import rand_unitary_ndarray, test_unitary_ndarray

# Cell
def identity_ham(t):
    iden = identity(2)
    return iden

# Cell
u0 = rand_unitary_ndarray((2,2))
evolution_time = 5
no_time_step_for_eval = 100