# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ihu": "00_core.ipynb",
         "y_der": "00_core.ipynb",
         "complex_random_sample": "01_reshape.ipynb",
         "rand_herm_ndarray": "02_herm.ipynb",
         "test_herm_ndarray": "02_herm.ipynb",
         "rand_unitary_ndarray": "03_unitary.ipynb",
         "test_unitary_ndarray": "03_unitary.ipynb"}

modules = ["core.py",
           "reshape.py",
           "herm.py",
           "unitary.py"]

doc_url = "https://TejasAvinashShetty.github.io/ihu/"

git_url = "https://github.com/TejasAvinashShetty/ihu/blob/master/"

def custom_doc_links(name): return None
