# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ihu": "00_core.ipynb",
         "y_der": "00_core.ipynb",
         "check_for_stupidity": "00_core.ipynb",
         "complex_random_sample": "01_reshape.ipynb",
         "rand_herm_ndarray": "02_herm.ipynb",
         "test_herm_ndarray": "02_herm.ipynb",
         "rand_unitary_ndarray": "03_unitary.ipynb",
         "test_unitary_ndarray": "03_unitary.ipynb",
         "zero_ham": "04_tests.ipynb",
         "u0": "04_tests.ipynb",
         "evolution_time": "04_tests.ipynb",
         "no_time_step_for_eval": "04_tests.ipynb",
         "identity_ham": "04_tests.ipynb",
         "H": "04_tests.ipynb",
         "psi0": "04_tests.ipynb",
         "times": "04_tests.ipynb",
         "mere_result": "04_tests.ipynb",
         "q_ham": "04_tests.ipynb",
         "psi0_ndarray": "04_tests.ipynb",
         "upsi": "04_tests.ipynb"}

modules = ["core.py",
           "reshape.py",
           "herm.py",
           "unitary.py",
           "04_tests.py"]

doc_url = "https://TejasAvinashShetty.github.io/ihu/"

git_url = "https://github.com/TejasAvinashShetty/ihu/blob/master/"

def custom_doc_links(name): return None
