# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"complex_random_sample": "01_reshape.ipynb"}

modules = ["reshape.py"]

doc_url = "https://TejasAvinashShetty.github.io/ihu/"

git_url = "https://github.com/TejasAvinashShetty/ihu/blob/master/"

def custom_doc_links(name): return None
