# AUTOGENERATED! DO NOT EDIT! File to edit: 03_unitary.ipynb (unless otherwise specified).

__all__ = []

# Cell
from numpy.random import random_sample
from numpy import array
from numpy.testing import assert_allclose